//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MECTRONICS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLASES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLASES()
        {
            this.MATRICULAS = new HashSet<MATRICULAS>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ID_PROFESOR { get; set; }
        public Nullable<int> ID_MATERIA { get; set; }
        public Nullable<int> ID_SALON { get; set; }
    
        public virtual MATERIAS MATERIAS { get; set; }
        public virtual PROFESORES PROFESORES { get; set; }
        public virtual SALONES SALONES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MATRICULAS> MATRICULAS { get; set; }
    }
}
