//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MECTRONICS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MectronicsEntities : DbContext
    {
        public MectronicsEntities()
            : base("name=MectronicsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ALUMNOS> ALUMNOS { get; set; }
        public virtual DbSet<CLASES> CLASES { get; set; }
        public virtual DbSet<MATERIAS> MATERIAS { get; set; }
        public virtual DbSet<MATRICULAS> MATRICULAS { get; set; }
        public virtual DbSet<PROFESORES> PROFESORES { get; set; }
        public virtual DbSet<SALONES> SALONES { get; set; }
    }
}
