//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MECTRONICS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATRICULAS
    {
        public int ID { get; set; }
        public Nullable<int> ID_CLASE { get; set; }
        public Nullable<int> ID_ALUMNO { get; set; }
        public Nullable<int> NOTA { get; set; }
        public System.DateTime FECHA_NOTA { get; set; }
    
        public virtual ALUMNOS ALUMNOS { get; set; }
        public virtual CLASES CLASES { get; set; }
    }
}
